# Generated by Django 2.1 on 2018-09-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInputsEng',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('item_status', models.TextField(blank=True, null=True)),
                ('input_user', models.TextField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('input_comment_eng', models.TextField(blank=True, null=True)),
                ('input_comment_esp', models.TextField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('seq_num', models.IntegerField(blank=True, null=True)),
                ('next_responsible', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Field Inputs View Eng',
                'db_table': 'field_inputs_eng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEng',
            fields=[
                ('item_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('installation', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('next_responsible', models.CharField(blank=True, max_length=80, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('applicability', models.BooleanField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Items English View',
                'db_table': 'item_eng',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('next_responsible', models.IntegerField(blank=True, null=True)),
                ('next_action', models.IntegerField(blank=True, null=True)),
                ('applicability', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Items Spanish View',
                'db_table': 'item_esp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Applicabilities',
                'db_table': 'applicability',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Criteria',
                'db_table': 'criteria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'db_table': 'evidence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FieldInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_user', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('input_comment_eng', models.TextField(blank=True, null=True)),
                ('seq_num', models.IntegerField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
                ('input_comment_esp', models.TextField(blank=True, null=True)),
                ('applicability', models.ForeignKey(blank=True, db_column='applicability', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Applicability')),
            ],
            options={
                'verbose_name_plural': 'Field Inputs',
                'db_table': 'field_inputs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.TextField(blank=True, null=True)),
                ('processing_center', models.TextField(blank=True, null=True)),
                ('platform_count', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, db_column='asset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Assets')),
            ],
            options={
                'verbose_name_plural': 'Installations',
                'db_table': 'installations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_responsible', models.IntegerField(blank=True, null=True)),
                ('next_action', models.IntegerField(blank=True, null=True)),
                ('applicable', models.BooleanField(blank=True, null=True)),
                ('next_action_temp', models.TextField(blank=True, null=True)),
                ('applicability', models.ForeignKey(blank=True, db_column='applicability', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Applicability')),
                ('criteria', models.ForeignKey(blank=True, db_column='criteria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Criteria')),
                ('installation', models.ForeignKey(blank=True, db_column='installation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Installations')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Priority',
                'db_table': 'priority',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.TextField(blank=True, null=True)),
                ('prefix', models.TextField(blank=True, null=True)),
                ('major', models.TextField(blank=True, null=True)),
                ('minor', models.TextField(blank=True, null=True)),
                ('part', models.TextField(blank=True, null=True)),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
                ('summary_eng', models.TextField(blank=True, null=True)),
                ('summary_esp', models.TextField(blank=True, null=True)),
                ('pep_responsible', models.TextField(blank=True, null=True)),
                ('absg_responsible', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True)),
                ('feild_verification', models.TextField(blank=True, null=True)),
                ('interview', models.TextField(blank=True, null=True)),
                ('sweetiening_plant', models.TextField(blank=True, null=True)),
                ('drill', models.TextField(blank=True, null=True)),
                ('crae', models.TextField(blank=True, null=True)),
                ('cases', models.TextField(blank=True, null=True)),
                ('abk_a2', models.TextField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
                ('type_user', models.BooleanField(blank=True, null=True)),
                ('type_rev', models.BooleanField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='items',
            name='recommendation',
            field=models.ForeignKey(blank=True, db_column='recommendation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Recommendations'),
        ),
        migrations.AddField(
            model_name='fieldinputs',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Items'),
        ),
        migrations.AddField(
            model_name='fieldinputs',
            name='item_status',
            field=models.ForeignKey(blank=True, db_column='item_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Status'),
        ),
    ]
