# Generated by Django 2.1 on 2018-09-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pemex_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='primary_reviewer',
            field=models.ForeignKey(blank=True, db_column='primary_reviewer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='criteria',
            field=models.ForeignKey(blank=True, db_column='criteria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Criteria'),
        ),
        migrations.AddField(
            model_name='items',
            name='installation',
            field=models.ForeignKey(blank=True, db_column='installation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Installations'),
        ),
        migrations.AddField(
            model_name='items',
            name='next_responsible',
            field=models.ForeignKey(blank=True, db_column='criteria_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='recommendation',
            field=models.ForeignKey(blank=True, db_column='recommendation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Recommendations'),
        ),
        migrations.AddField(
            model_name='filemap',
            name='evidence',
            field=models.ForeignKey(blank=True, db_column='evidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Evidences'),
        ),
        migrations.AddField(
            model_name='filemap',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Documents'),
        ),
        migrations.AddField(
            model_name='filemap',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Items'),
        ),
        migrations.AddField(
            model_name='filemap',
            name='map_user',
            field=models.ForeignKey(blank=True, db_column='criteria_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldinputs',
            name='input_user',
            field=models.ForeignKey(blank=True, db_column='primary_reviewer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldinputs',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Items'),
        ),
        migrations.AddField(
            model_name='fieldinputs',
            name='item_status',
            field=models.ForeignKey(blank=True, db_column='item_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Status'),
        ),
        migrations.AddField(
            model_name='evidences',
            name='evidence_user',
            field=models.ForeignKey(blank=True, db_column='evidence_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidences',
            name='item_id',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Items'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria_user',
            field=models.ForeignKey(blank=True, db_column='criteria_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
