# Generated by Django 2.1 on 2018-09-21 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pemex_app', '0003_remove_fieldinputs_input_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldinputs',
            name='input_user',
            field=models.ForeignKey(blank=True, db_column='primary_reviewer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
