# Generated by Django 2.1 on 2018-09-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemex_app', '0003_documents_filestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('desc_eng', models.TextField(blank=True, null=True)),
                ('desc_esp', models.TextField(blank=True, null=True)),
                ('evidence_user', models.IntegerField(blank=True, null=True)),
                ('evidence_date', models.DateTimeField(blank=True, null=True)),
                ('trans_eng', models.BooleanField(blank=True, null=True)),
                ('trans_esp', models.BooleanField(blank=True, null=True)),
                ('criteria', models.ForeignKey(blank=True, db_column='criteria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Criteria')),
                ('installation', models.ForeignKey(blank=True, db_column='installation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Installations')),
                ('recommendation', models.ForeignKey(blank=True, db_column='recommendation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Recommendations')),
            ],
            options={
                'verbose_name_plural': 'Evidences',
                'db_table': 'evidences',
                'managed': True,
            },
        ),
    ]
