# Generated by Django 2.1 on 2018-09-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemex_app', '0005_auto_20180920_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_user', models.TextField(blank=True, null=True)),
                ('map_date', models.DateTimeField(blank=True, null=True)),
                ('map_comment', models.TextField(blank=True, null=True)),
                ('evidence', models.ForeignKey(blank=True, db_column='evidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Evidences')),
                ('file', models.ForeignKey(blank=True, db_column='file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Documents')),
                ('item', models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pemex_app.Items')),
            ],
            options={
                'db_table': 'filemap',
                'managed': True,
            },
        ),
    ]
