# Generated by Django 2.1 on 2018-09-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemex_app', '0007_auto_20180923_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldInputsView',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('status_eng', models.TextField(blank=True, null=True)),
                ('status_esp', models.TextField(blank=True, null=True)),
                ('int_comment_eng', models.TextField(blank=True, null=True)),
                ('int_comment_esp', models.TextField(blank=True, null=True)),
                ('ext_comment_eng', models.TextField(blank=True, null=True)),
                ('ext_comment_esp', models.TextField(blank=True, null=True)),
                ('deficiencies_eng', models.TextField(blank=True, null=True)),
                ('deficiencies_esp', models.TextField(blank=True, null=True)),
                ('input_user', models.IntegerField(blank=True, null=True)),
                ('input_date', models.DateTimeField(blank=True, null=True)),
                ('seq_num', models.IntegerField(blank=True, null=True)),
                ('next_responsible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field_inputs_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('item_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('installation', models.TextField(blank=True, null=True)),
                ('rec_id', models.TextField(blank=True, null=True)),
                ('rec_eng', models.TextField(blank=True, null=True)),
                ('rec_esp', models.TextField(blank=True, null=True)),
                ('criteria_prefix', models.TextField(blank=True, null=True)),
                ('crit_eng', models.TextField(blank=True, null=True)),
                ('crit_esp', models.TextField(blank=True, null=True)),
                ('next_responsible', models.CharField(blank=True, max_length=80, null=True)),
                ('count_evidence', models.IntegerField(blank=True, null=True)),
                ('pct_complete', models.TextField(blank=True, null=True)),
                ('applicability', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Items View',
                'db_table': 'item_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='evidences',
            name='generic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
