# Generated by Django 2.1 on 2018-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemex_app', '0008_auto_20180921_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemap',
            old_name='map_comment',
            new_name='doc_comment_eng',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_comment_eng',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_comment_esp',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='evidence_date',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='evidence_user',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='trans_eng',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='trans_esp',
        ),
        migrations.AddField(
            model_name='filemap',
            name='doc_comment_esp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemap',
            name='trans_eng',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemap',
            name='trans_esp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
